CREATE TABLE prod.uoms (
    uom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uom_name VARCHAR(255) NOT NULL,
    uom_code VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_date TIMESTAMP NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_by BIGINT,
    deleted_date TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);
