services:
  - type: web
    name: recipe-backend
    runtime: docker
    repo: https://github.com/farahani456/recipe-backend.git
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
